ifndef::springdoc-aggregate[]
= Getting Started with springdoc-openapi
:toc: left
:toclevels: 3
:sectanchors:
:icons: font
:hide-uri-scheme:
endif::[]

[[getting-started]]
== Getting Started

For the integration between spring-boot and swagger-ui, add the library to the list of your project dependencies (No additional configuration is needed)

=== Maven
[source,xml, subs="attributes+"]
----
   <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>{springdoc-version}</version>
   </dependency>
----

=== Gradle 
[source,gradle, subs="attributes+"]
implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:{springdoc-version}'


For example, using version 3.0.3:
[source,gradle]
----
implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
----

This will automatically deploy swagger-ui to a spring-boot application:

*   Documentation will be available in HTML format, using the official link:https://github.com/swagger-api/swagger-ui.git[swagger-ui jars, window="_blank"]
*   The Swagger UI page will then be available at `\http://server:port/context-path/swagger-ui.html` and the OpenAPI description will be available at the following url for json format: `\http://server:port/context-path/v3/api-docs`
**  server: The server name or IP
**  port: The server port
**  context-path: The context path of the application
*   Documentation will be available in yaml format as well, on the following path : /v3/api-docs.yaml

TIP: For custom path of the swagger documentation in HTML format, add a custom springdoc property, in your spring-boot configuration file: .


[source,properties]
----
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
----

include::{docdir}/_ad-in-article.adoc[]
