ifndef::springdoc-aggregate[]
= springdoc-openapi Configuration Properties (v1)
:toc: left
:toclevels: 3
:sectanchors:
:icons: font
:hide-uri-scheme:
:docinfodir: v1

IMPORTANT: You are reading the archived documentation for *springdoc-openapi v1* (Spring Boot 1.x and 2.x), which is no longer maintained. See the https://springdoc.org[current springdoc-openapi documentation] for supported releases.
endif::[]

:springdoc-aggregate:
[[properties]]
== Springdoc-openapi Properties

`springdoc-openapi` relies on standard link:https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config[spring configuration properties, window="_blank"] (yml or properties) using the standard files locations.


=== springdoc-openapi core properties

include::v1/core-properties.adoc[]

=== swagger-ui properties
- The support of the swagger-ui properties is available on `springdoc-openapi`.  See link:https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/[Official documentation, window="_blank"].

- You can use the same swagger-ui properties in the documentation as Spring Boot properties.

NOTE: All these properties should be declared with the following prefix: `springdoc.swagger-ui`

include::v1/ui-properties.adoc[]

